---
title: "Análisis de Transacciones"
author: "Tomas Edu Tantalean Sarmiento"
date: "r format(Sys.time(), '%d/%m/%Y')"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    collapsed: true
    smooth_scroll: true
    theme: journal
    highlight: kate
    df_print: paged
    code_folding: show
---

```{r,warning=FALSE, include=FALSE}
library(tidyverse)
library(rio)
```

# BASE DE DATO

```{r}
transacciones <- import("base_transacciones.csv", sheet = "base_transacciones")
transacciones
```

## BASE DE DATOS LIMPIO

```{r}
transacciones_corregido <- transacciones %>%
  mutate(
    id_transaccion = as.integer(abs(id_transaccion)),
    id_cliente = as.integer(abs(id_cliente)),
    monto = as.numeric(ifelse(is.na(monto), -1, monto)),
    tipo_transaccion = as.character(ifelse(is.na(tipo_transaccion), "no identificado", tipo_transaccion)),
    estado_transaccion = as.character(ifelse(is.na(estado_transaccion), "no identificado", estado_transaccion)),
    fecha_transaccion = as.Date(fecha_transaccion),
    fecha_transaccion = format(fecha_transaccion, "%Y-%m-%d")
  )
transacciones_corregido
```

### REGISTRO DE TRANSICIONES FILTRADOS

```{r}
transacciones_con_dias <- transacciones_corregido %>%
  arrange(id_cliente, fecha_transaccion) %>%
  group_by(id_cliente) %>%
  mutate(dias_desde_ultima_transaccion = difftime(max(fecha_transaccion), fecha_transaccion, units = "days")) %>%
  ungroup()
transacciones_con_dias

transacciones_completadas <- transacciones_con_dias %>%
  filter(estado_transaccion == "Completada")
transacciones_completadas

limite_monto_anormal <- mean(transacciones_con_dias$monto, na.rm = TRUE) + 3 * sd(transacciones_con_dias$monto, na.rm = TRUE)

transacciones_anormales <- transacciones_con_dias %>%
  filter(monto > limite_monto_anormal)
summary(transacciones_anormales$monto)

transacciones_anormales
```
